Mpesa/urls.py
from django.urls import path

from Mpesa import views


app_name = "Mpesa"

urlpatterns = [
    path('', views.home, name="home"),
    path('token', views.token, name='token'),
    path('pay', views.pay, name='pay'),
    path('stk', views.stk, name="stk")

]

mpesaApi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('Mpesa.urls')),
    path('admin/', admin.site.urls),
]

Mpesa/models.py
from django.db import models

# Create your models here.

Mpesa/views.py
from django.http import HttpResponse
import requests
from requests.auth import HTTPBasicAuth
import json
from .credentials import MpesaAccessToken, LipanaMpesaPpassword

from django.shortcuts import render, redirect
from django.contrib import messages


def home(request):
    return render(request, 'home.html', {'navbar': 'home'})


def token(request):
    consumer_key = 'UANGN6wpk65xpX19SSBqVdqlf8rpBuTD'
    consumer_secret = 'izAKA2MgIbkBbByO'
    api_URL = 'https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'

    r = requests.get(api_URL, auth=HTTPBasicAuth(
        consumer_key, consumer_secret))
    mpesa_access_token = json.loads(r.text)
    validated_mpesa_access_token = mpesa_access_token["access_token"]

    return render(request, 'token.html', {"token": validated_mpesa_access_token})


def pay(request):
    if request.method == "POST":
        phone = request.POST['phone']
        amount = request.POST['amount']
        access_token = MpesaAccessToken.validated_mpesa_access_token
        api_url = "https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
        headers = {"Authorization": "Bearer %s" % access_token}
        request = {
            "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
            "Password": LipanaMpesaPpassword.decode_password,
            "Timestamp": LipanaMpesaPpassword.lipa_time,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": phone,
            "PartyB": LipanaMpesaPpassword.Business_short_code,
            "PhoneNumber": phone,
            "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
            "AccountReference": "Sheila Mahinda",
            "TransactionDesc": "Web Development Charges"
        }

    response = requests.post(api_url, json=request, headers=headers)
    return HttpResponse("success")


def stk(request):
    return render(request, 'pay.html', {'navbar': 'stk'})

Mpesa/templates/home.html
{% extends 'layout.html' %}


{% load static %}

  {% block body %}

	<div class="container">
       <h2 class="mt-5">Django MPESA STK Push </h2>

    Enjoy Fellas
    </div>



  {% endblock %}

Mpesa/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MPESA</title>
      <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <body>




<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'Mpesa:home' %}">Django </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class=" me-auto mb-2 mb-lg-0">

      </ul>
      <span class="navbar-text">

        <ul class="navbar-nav">
             <li class="nav-item">
          <a class="nav-link {% if navbar == 'home' %} activated {% endif %}" aria-current="page" href="{% url 'Mpesa:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Mpesa:token' %}">Token</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if navbar == 'stk' %} activated {% endif %}" href="{% url 'Mpesa:stk' %}">Pay here</a>
        </li>
        </ul>

      </span>
    </div>
  </div>
</nav>


  {% block body %}



  {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </body>
</html>

Mpesa/templates/pay.html
{% extends 'layout.html' %}

{% load static %}

  {% block body %}

<div class="container">

    <div class="row">


              <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                    <strong>{{message}}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>

        <div class="col-md-5">

            <form method="POST" action="{% url 'Mpesa:pay'%}">
                {% csrf_token %}

                <label class="form-label mt-5">Phone Number</label>
                <input type="number" name="phone" value="254" class="form-control">

                <label class="form-label mt-5">Amount</label>
                <input type="number" name="amount" class="form-control">

                <input type="submit" name="submit" class="form-control mt-5 btn btn-success" value="pay">
            </form>

        </div>

        <div class="col-md-7">

        </div>

    </div>
</div>

 {% endblock %}

Mpesa/templates/token.html
{% extends 'layout.html' %}


{% load static %}

  {% block body %}

	<div class="container">

         <form>

             <h3 class="form-label mt-5">MPESA Access Token:</h3>
             <h5  class="form-label mt-5">{{ token }}</h5>

         </form>

    </div>


  {% endblock %}